version: '0.9'

networks:
  spbackend-dev:
volumes:
  postgres-data:

services:
  spbackend:
    image: trancezero/spbackend:dev
    env_file: 
      - .env
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: gunicorn spbackend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/home/spbackend
      - ./productionfiles:/home/staticfiles
      - ./media:/home/mediafiles
    ports:
      - :8000
    depends_on:
      - spdb
    networks:
      - spbackend-dev
  spdb:
    image: postgres:15
    env_file: 
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRE_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRE_PASSWORD}
      - POSTGRES_DB=${POSTGRE_HOST}
    ports:
      # port $POSTGRE_PORT for connection on local computer
      - ${POSTGRE_PORT}:5432
    networks:
      - spbackend-dev
  spnginx:
    image: trancezero/spnginx
    env_file: 
      - .env
    build: ./spnginx
    volumes:
      - ./productionfiles:/home/staticfiles
      - ./media:/home/mediafiles
    ports:
      # port for debugging nginx on local computer
      - ${NGINX_PORT}:80
    depends_on:
      - spbackend
    networks:
      - spbackend-dev