version: '0.2'

volumes:
  postgres-data:
  spbackend-data:
  static_volume:
  media_volume:
networks:
  spbackend-back:

services:
  spbackend:
    image: trancezero/spbackend:v0.7
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn spbackend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - spbackend-data:/home/spbackend
      - static_volume:/home/staticfiles
      - media_volume:/home/mediafiles
    ports:
      - ${DJANGO_PORT}:8000
    depends_on:
      - spdb
    networks:
      - spbackend-back
  spdb:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRE_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRE_PASSWORD}
      - POSTGRES_DB=${POSTGRE_HOST}
    ports:
      # port 5432 for connection on local computer
      - 5432:5432
    networks:
      - spbackend-back
  spnginx:
    image: trancezero/spnginx
    build: ./spnginx
    volumes:
      - static_volume:/home/staticfiles
      - media_volume:/home/mediafiles
    ports:
      # port for debugging nginx on local computer
      - ${NGINX_PORT}:80
    depends_on:
      - spbackend
    networks:
      - spbackend-back
