# Generated by Django 4.2 on 2024-11-22 06:19

import cluster.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('page_type', models.CharField(choices=[('s', 'School'), ('p', 'Philosopher')], default='p', max_length=1)),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Untitled Section', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('section_type', models.CharField(choices=[('t', 'Text'), ('i', 'Image'), ('f', 'File'), ('n', 'Footnote'), ('r', 'Read More')], default='t', max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to=cluster.models.section_file_path)),
                ('file', models.FileField(blank=True, null=True, upload_to=cluster.models.section_file_path)),
                ('text', models.TextField(blank=True, null=True)),
                ('args', models.CharField(blank=True, max_length=256, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluster.page')),
                ('parent_section_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cluster.section')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluster.section')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('end_page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indegree', to='cluster.page')),
                ('start_page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outdegree', to='cluster.page')),
            ],
        ),
        migrations.CreateModel(
            name='DefinitionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=36)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluster.section')),
            ],
        ),
    ]
