# Generated by Django 4.2 on 2024-09-28 17:15

import cluster.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Philosopher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Unknown Philosopher", max_length=100),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=cluster.models.philosopher_file_path,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_edit", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Unknown School", max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_edit", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(default="Untitled Section", max_length=100),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=cluster.models.section_file_path,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=cluster.models.section_file_path,
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                ("args", models.CharField(blank=True, max_length=256, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_edit", models.DateTimeField(auto_now=True)),
                (
                    "philosopher_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cluster.philosopher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=36)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "section_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cluster.section",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Relation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=36)),
                (
                    "description",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_edit", models.DateTimeField(auto_now=True)),
                (
                    "end_philosopher_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indegree",
                        to="cluster.philosopher",
                    ),
                ),
                (
                    "start_philosopher_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outdegree",
                        to="cluster.philosopher",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="philosopher",
            name="school_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cluster.school"
            ),
        ),
        migrations.CreateModel(
            name="Development",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=36)),
                (
                    "description",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_edit", models.DateTimeField(auto_now=True)),
                (
                    "end_school_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indegree",
                        to="cluster.school",
                    ),
                ),
                (
                    "start_school_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outdegree",
                        to="cluster.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Affiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=36)),
                (
                    "description",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_edit", models.DateTimeField(auto_now=True)),
                (
                    "end_school_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cluster.school"
                    ),
                ),
                (
                    "start_philosopher_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cluster.philosopher",
                    ),
                ),
            ],
        ),
    ]
