# Generated by Django 4.2 on 2024-11-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('t', 'Text'), ('i', 'Image'), ('f', 'File'), ('n', 'Footnote'), ('r', 'Read More')], default='t', max_length=1, null=True),
        ),
    ]
