# Generated by Django 4.2 on 2024-11-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='philosopher',
            name='title',
        ),
        migrations.RemoveField(
            model_name='school',
            name='title',
        ),
        migrations.AddField(
            model_name='philosopher',
            name='name',
            field=models.CharField(default='asdfasf', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='philosopher',
            name='slug',
            field=models.SlugField(default='ccc', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(default='default-school', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(default='slug', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='scs', max_length=100),
            preserve_default=False,
        ),
    ]
