# Generated by Django 4.2 on 2024-11-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0004_section_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('t', 'Text'), ('i', 'Image'), ('f', 'File'), ('n', 'Footnote'), ('r', 'Read More'), ('a', 'Arrow'), ('m', 'Page Meta')], default='t', max_length=1),
        ),
    ]
