# Generated by Django 4.2 on 2024-11-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0005_alter_section_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='relation_type',
            field=models.CharField(choices=[('a', 'Affiliation'), ('d', 'Development'), ('i', 'Influence')], default='a', max_length=1),
        ),
    ]
