# Generated by Django 4.2 on 2024-11-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0006_relation_relation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='name',
        ),
        migrations.AlterField(
            model_name='relation',
            name='relation_type',
            field=models.CharField(choices=[('a', 'Affiliation'), ('d', 'Development'), ('i', 'Influence'), ('r', 'Rejection')], default='a', max_length=1),
        ),
    ]
